# Generated by Django 5.1.5 on 2025-02-05 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid mobile number.", regex="^\\d{10}$"
                    )
                ],
            ),
        ),
    ]
