# Generated by Django 5.1.5 on 2025-02-10 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_user_mobile_number_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid mobile number with country code.",
                        regex="^\\+\\d{1,4}\\d{10}$",
                    )
                ],
            ),
        ),
    ]
